### ISSUE TITLE
Not clear document: word

### ISSUE THREAD

**Issue by jzen188** [summanlp/textrank#1]
Hi, I am interested in using summa.keywords for toy data analysis.
It is not a real issue here.

# What I can input to words argument
keywords(words = None) 

# You mentioned for a better keywords extraction, import Pattern.
I have imported already. So, the function just called it to extract NN, JJ only, what if I want to include Verb in the same time? 

Thank you

**Comment by fedelopez77** [comment]
Hello,
As you may see in the [More examples section](https://github.com/summanlp/textrank#more-examples), it says:
- Define length of the summary by aproximate number of words (also available in `keywords`):

    >>> summarize(text, words=50)

In the example, you would get a summary of no more than 50 words.

For your second question, you can set the filters modifying [this line of code](https://github.com/summanlp/textrank/blob/master/summa/keywords.py#L15), or if you have installed [summa](https://pypi.python.org/pypi/summa/0.0.7), you can simply do:

    >>> from summa import keywords
    >>> keywords.INCLUDING_FILTER = ['NN', 'JJ', 'VB']

Notice that you can also set excluding filters.

Hope that helps.
Regards.

**Comment by jzen188** [comment]
really good informative...
Thanks a lot...
I like your tools...

Best,
