### ISSUE TITLE
why i got empty string?

### ISSUE THREAD

**Issue by HHself** [summanlp/textrank#28]
>>> from summa.summarizer import summarize
>>> text = """Automatic summarization is the process of reducing a text document with a computer program in order to create a summary that retains the most important points of the original document. As the problem of information overload has grown, and as the quantity of data has increased, so has interest in automatic summarization.Technologies that can make a coherent summary take into account variables such as length, writing style and syntax. An example of the use of summarization technology is search engines such as Google. Document summarization is another."""
>>> summarize(text)
''

**Comment by fbarrios** [comment]
Because there is a missing space in `summarization.Technologies`. Therefore the text sample doesn't have enough sentences, and in that case we return empty string.
