### ISSUE TITLE
Pattern not compatible with Python>2.7

### ISSUE THREAD

**Issue by mukund109** [summanlp/textrank#30]
Both lemmatization and pos filtering require the pattern package which is not available for python>2.7

Any fix coming soon or would we need to wait for pattern3 to finish being developed?

**Comment by fedelopez77** [comment]
`pattern` is only used for POS filtering, lemmatization is provided by `SnowballStemmer`.
Currently Pattern is on development for Python3. On our next release we will see whether we use it, or we decide to go for some other module for POS tagging.
