### ISSUE TITLE
Create a better CLI

### ISSUE THREAD

**Issue by fbarrios** [summanlp/textrank#38]
To use the application in v1.0.0 from command line, the user needs to execute:

```
textrank -s 0 -t /home/fbarrios/sample.txt   # for a summary
textrank -s 1 -t /home/fbarrios/sample.txt   # for keywords
```

Which is awful. The commands should be:

```
textrank --summarize /home/fede/sample.txt
textrank --keywords /home/fede/sample.txt
```

For compatibility reasons, the _old_ API should be kept, as well, so either the `--summarize` or the `--keywords` parameter or a value for `-s` should be present.

**Comment by adhaamehab** [comment]
Hi @fbarrios anyone working on this? I'm willing to solve it.

**Comment by fbarrios** [comment]
Hi @adhaamehab, your contributions will be very welcomed.

No one is working on this because it was somewhat blocked by #42, which I just merged. So feel free to start working on this if you want :)
