### ISSUE TITLE
Error of graph module

### ISSUE THREAD

**Issue by bhavsarpratik** [summanlp/textrank#5]
Can you tell me which module is this 'graph' ?

File "C:\Users\Pratik\AppData\Local\Programs\Python\Python35\lib\site-packages\summa\__init__.py", line 2, in <module>
    from summa import commons, export, graph, keywords, pagerank_weighted, \
  File "C:\Users\Pratik\AppData\Local\Programs\Python\Python35\lib\site-packages\summa\commons.py", line 2, in <module>
    from graph import Graph
ImportError: No module named 'graph'

**Comment by infomiho** [comment]
I have the same issue on Xubuntu 16.10.

```
  File "main.py", line 9, in <module>
    from summa.summarizer import *
  File "/usr/local/lib/python3.5/dist-packages/summa/__init__.py", line 2, in <module>
    from summa import commons, export, graph, keywords, pagerank_weighted, \
  File "/usr/local/lib/python3.5/dist-packages/summa/commons.py", line 2, in <module>
    from graph import Graph
ImportError: No module named 'graph'
```

**Comment by paladini** [comment]
Same issue here using Elementary OS 0.4:

`Traceback (most recent call last):
  File "get_fb_page_status.py", line 11, in <module>
    from summa.keywords import keywords # Keyword extraction
  File "/usr/local/lib/python3.5/dist-packages/summa/__init__.py", line 2, in <module>
    from summa import commons, export, graph, keywords, pagerank_weighted, \
  File "/usr/local/lib/python3.5/dist-packages/summa/commons.py", line 2, in <module>
    from graph import Graph
ImportError: No module named 'graph'`

Any workaround?

**Comment by fbarrios** [comment]
Should be [this](https://github.com/summanlp/textrank/blob/master/summa/graph.py#L137). Did you install the package using pip?

**Comment by jeanbmar** [comment]
The code is not intended to run with Python 3. 

To do so I had to do many changes like change print x calls to print(x), xrange to range, prefixing imports with dots (e.g. from graph becomes from .graph), etc.

**Comment by lakshyakhanna** [comment]
@jeanbmar Can you please share the updated python code. I have to run text summarizer on Python3 but it does not support Python 3.

**Comment by shubhendu-shekhar** [comment]
@jeanbmar Sir, could you please upload the Python 3 code !

**Comment by kavin26** [comment]
is the issue of not running in python 3.x still exists? guys is there any workaround for using `summa.summarizer` for text summarization tasks?

**Comment by dondon2475848** [comment]
Maybe you can clone latest  github version.

**Comment by fbarrios** [comment]
@kavin26 All 0.x releases are for Python 2.7. We are currently working on the first version for 3.5 to be released soon. It is currently available in the master branch.

**Comment by kavin26** [comment]
thank you very much @dondon2475848 @fbarrios i shall look into it

**Comment by fbarrios** [comment]
Closing this as the new release is for Python 3.
