### ISSUE TITLE
url's

### ISSUE THREAD

**Issue by antonysama** [summanlp/textrank#74]
Thank you, I appreciate what this does for text summarization -- in particular its simplicity. Can you recommend a similar one for summarizing content in url's (such as news sites)? (If not, I can always find a way to scrape the url into a text file and use summa)

**Comment by fbarrios** [comment]
Hi! Thank you for the kind words.

I know of this project: https://github.com/pastine/resumidor-estatal/, that uses this to summarize news articles fetched by https://github.com/andreskrey/empleadoEstatalBot, but afaik it's only used for fetching Argentine media news articles. And is developed in php.

If you don't really care about the content, the Gensim project has a module to experiment with Wikipedia: https://radimrehurek.com/gensim/wiki.html
