### ISSUE TITLE
extremely slow for long texts

### ISSUE THREAD

**Issue by WuTheFWasThat** [summanlp/textrank#82]
i'm trying to run textrank on a book, and it's taking a very long time. 
by comparison, https://github.com/DerwenAI/pytextrank was quite fast (though i'm not sure if what i did was a fair comparison)

**Comment by WuTheFWasThat** [comment]
oh wow, it also was using a huge amount of RAM

**Comment by fedelopez77** [comment]
Hi Jeff,
You can try our version of the algorithm implemented in [Gensim](https://radimrehurek.com/gensim_3.8.3/summarization/summariser.html). 
That is probably faster.

**Comment by WuTheFWasThat** [comment]
thanks, much much faster!
